name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: requirements
        path: github-actions-lab1-q1/requirements.txt
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
